name: seamless-dask
channels:
  - conda-forge
dependencies:
  - python=3.12.* # for pure-dask. Seamless transformations should be more resistant
  - aiofiles
  - dask
  - distributed
  - aiohttp
  - pyyaml
  - numpy
  - pip
  - pip:
      - orjson
      - frozendict
      - dask_jobqueue
      - -e .
      - -e ./seamless-base
      - -e ./seamless-transformer
      - -e ./seamless-config
      - -e ./seamless-remote
