[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seamless-dask"
version = "0.0.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "dask",
    "distributed",
]